[profile.default]
  evm_version = "shanghai"
  ffi = true
  fs_permissions = [{ access = "read", path = "./test/data/" }, { access = "read", path = "./snark-verifiers" }, { access = "read", path = "./script/config/" }]
  libs = ['lib']
  optimizer = true
  optimizer_runs = 1_000_000
  out = 'out'
  # solc = "0.8.19"
  src = 'src'
  libraries = ["src/library/GoldilocksPoseidon.sol:GoldilocksPoseidon:0x81d8aaf7d4CfcC07d4343C47fb0100a76423f787"]


[profile.default.optimizer_details]
  constantOptimizer = false
  yul = false

  # See more config options https://github.com/foundry-rs/foundry/tree/master/config

  # Configures permissions for cheatcodes that touch the filesystem like `vm.writeFile`
  # `access` restricts how the `path` can be accessed via cheatcodes
  #    `read-write` | `true`   => `read` + `write` access allowed (`vm.readFile` + `vm.writeFile`)
  #    `none`| `false` => no access
  #    `read` => only read access (`vm.readFile`)
  #    `write` => only write access (`vm.writeFile`)
  # The `allowed_paths` further lists the paths that are considered, e.g. `./` represents the project root directory
  # By default _no_ fs access permission is granted, and _no_ paths are allowed
  # following example enables read access for the project dir _only_:
  #       `fs_permissions = [{ access = "read", path = "./"}]`

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  goerli = "${GOERLI_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "multi"
  tab_width = 4
  wrap_comments = false